export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_SUCCESS_ACTION = 'LOGIN_SUCCESS_ACTION';
export const LOGIN_ERROR_ACTION = 'LOGIN_ERROR_ACTION';
export const USER_AUTH_VALIDATION = 'USER_AUTH_VALIDATION';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
